"""``hermes channel-skills`` argparse wiring."""

from __future__ import annotations

from typing import Callable

from hermes_cli.subcommands._shared import add_json_flag, add_yes_flag


def build_channel_skills_parser(subparsers, *, cmd_channel_skills: Callable) -> None:
    parser = subparsers.add_parser(
        "channel-skills",
        help="Inspect and manage generated channel-specific skills",
        description="Inspect, validate, remove, and repair channel-specific skills generated by the gateway.",
    )
    parser.add_argument("--json", dest="root_json", action="store_true", help="Output JSON")
    actions = parser.add_subparsers(dest="action")

    list_parser = actions.add_parser("list", help="List registered channel skills")
    list_parser.add_argument("--status", choices=["ready", "missing", "corrupt", "manual_override", "generating", "configured", "invalid"], default=None)
    list_parser.add_argument("--source", choices=["static", "generated"], default=None)
    list_parser.add_argument("--all", action="store_true", help="Include static bindings")
    list_parser.add_argument("--effective", action="store_true", help="Show resolved effective skills")
    add_json_flag(list_parser, "Output JSON")

    effective_parser = actions.add_parser("effective", help="Show skills applied to a channel")
    effective_parser.add_argument("channel_id", help="Channel ID")
    effective_parser.add_argument("--parent-id", default=None, help="Parent channel ID for thread resolution")
    add_json_flag(effective_parser, "Output JSON")

    validate_parser = actions.add_parser("validate", help="Validate static and generated channel skills")
    add_json_flag(validate_parser, "Output JSON")

    for name, help_text in (("show", "Show channel skill metadata"), ("inspect", "Show metadata and SKILL.md content")):
        child = actions.add_parser(name, help=help_text)
        child.add_argument("channel_id", help="Channel ID")
        add_json_flag(child, "Output JSON")

    remove_parser = actions.add_parser("remove", help="Detach a channel skill from the registry")
    remove_parser.add_argument("channel_id", help="Channel ID")
    remove_parser.add_argument("--delete-skill", action="store_true", help="Also delete the generated SKILL.md")
    add_yes_flag(remove_parser, "Required with --delete-skill")
    add_json_flag(remove_parser, "Output JSON")

    regenerate_parser = actions.add_parser("regenerate", help="Regenerate a channel skill")
    regenerate_parser.add_argument("channel_id", help="Channel ID")
    regenerate_parser.add_argument("--force", action="store_true", help="Overwrite a manually edited skill")
    regenerate_parser.add_argument("--dry-run", action="store_true", help="Generate and display without writing")
    regenerate_parser.add_argument("--backup", action="store_true", help="Back up the current SKILL.md before writing")
    add_json_flag(regenerate_parser, "Output JSON")

    repair_parser = actions.add_parser("repair", help="Find registry and SKILL.md inconsistencies")
    repair_parser.add_argument("--apply", action="store_true", help="Apply safe registry repairs")
    add_json_flag(repair_parser, "Output JSON")

    bind_parser = actions.add_parser("bind", help="Create a static channel-skill binding")
    bind_parser.add_argument("channel_id", help="Channel ID")
    group = bind_parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--profile", help="Profile name")
    group.add_argument("--skill", action="append", help="Skill name; repeat for multiple skills")

    unbind_parser = actions.add_parser("unbind", help="Remove a static channel-skill binding")
    unbind_parser.add_argument("channel_id", help="Channel ID")

    policy_parser = actions.add_parser("policy", help="Manage automatic channel-skill generation")
    policy_actions = policy_parser.add_subparsers(dest="policy_action", required=True)
    policy_show = policy_actions.add_parser("show", help="Show generation policy")
    add_json_flag(policy_show, "Output JSON")
    policy_actions.add_parser("enable", help="Enable automatic generation")
    policy_actions.add_parser("disable", help="Disable automatic generation")

    parser.set_defaults(func=cmd_channel_skills)
